### ISSUE TITLE
textfsm templates

### ISSUE THREAD

**Issue by jedelman8** [kyokeefesally/bosun#3]
Hi there, nice templates you have :).  It would be nice to attribute the templates to https://github.com/networktocode/ntc-templates (plus it'll help you and others using your code stay up to date as we release more templates).  Either way, glad you found them useful and cool application.  BTW, we are based out of WeWork in NYC too.  Maybe we can find a way to work together.  Jason

**Comment by kyokeefesally** [comment]
Yes, my bad!  Updated README.  That's awesome!  I saw you were based in NYC, but didn't know you worked out of WeWork.  Which building?  Would be great to meet up and chat.  I'm free the week of 8/8.  What's your schedule look like?

Are you coming to Summer Camp --> http://summercamp.wework.com? 

My email is kyle at wework dot com


Best,

Kyle
